# Generated by Django 5.1.15 on 2026-06-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id_card',
            field=models.ImageField(blank=True, null=True, upload_to='student_id_cards/%Y/%m/', verbose_name='学生证照片'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='审核备注'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('unverified', '未认证'), ('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], db_index=True, default='unverified', max_length=20, verbose_name='认证状态'),
        ),
    ]
