# Generated by Django 5.1.15 on 2026-06-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_recalled',
            field=models.BooleanField(db_index=True, default=False, help_text='消息是否已被发送者撤回', verbose_name='已撤回'),
        ),
        migrations.AddField(
            model_name='message',
            name='recalled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='撤回时间'),
        ),
    ]
